name: CI
on: pull_request

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.15.0"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt-get update
          sudo apt-get install libatk-bridge2.0-0

      - run: yarn install

      - name: Set Sched's API token env
        run: echo "SCHED_ACCESS_TOKEN=${{ secrets.SCHED_ACCESS_TOKEN }}" >> .env.production

      # Verify it compiles
      - run: yarn build

      # Doesn't pass ATM
      # - run: yarn tsc --noEmit
